### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by freyastreamlit** [whitphx/streamlit-component-template-react-hooks#104] opened 2023-03-14 16:48 UTC
HI,

Attempted to use this template, but after an `npm install` getting a Typescript error in one of the dependencies

```
TypeScript error in /.../frontend/node_modules/@types/babel__traverse/index.d.ts(68,50):
']' expected.  TS1005

    66 | }
    67 | 
  > 68 | export type ArrayKeys<T> = keyof { [P in keyof T as T[P] extends any[] ? P : never]: P };
       |                                                  ^
    69 | 
    70 | export class Scope {
    71 |     constructor(path: NodePath, parentScope?: Scope);
```

Do you get this at your end? Suggestions?

**Comment by whitphx** [comment] 2023-03-17 16:24
Hi, thank you for reporting this and sending a PR!
Actually, I couldn't reproduce this error, so your PR is so helpful that saves me investigating the root cause!

---

Appendix:
The commands I tested
```
mkdir react-template-test
cd react-template-test
cp -r /path/to/streamlit-component-template-react-hooks/template .
cd template/my_component/frontend
rm -rf node_modules
rm -rf build
npm install
```

**Comment by whitphx** [comment] 2023-03-17 16:27
As I merged your PR (thanks again!), let me close this issue.
Please reopen it or create a new one if you find some problems again :)

**Closed by whitphx** 2023-03-17 16:27 UTC
